## üéã Pandas b√°sico
La documentaci√≥n oficial de pandas esta aqu√≠: <a href="https://pandas.pydata.org/docs/">Pandas reference</a>

Importa pandas como ***pd***

In [37]:
import pandas as pd
pd.__version__

'1.4.4'

Importar numpy as **np**

In [38]:
import numpy as np
np.__version__

'1.22.4'

Importar thinker as **tk**

In [39]:
import tkinter as tk

Importa base de datos

In [40]:
datos = pd.read_csv('Datos3.csv', sep=';')

Revisar el head del dataframe (usar el m√©tdodo head())

In [41]:
datos.head()

      Nombre  Peso  Hamburguesa  Pizza  Perro
0  Christian    54            8      7      9
1      David    88           10      2      6
2      Jamez    70            9      2      8
3     Daniel    80            5      2      8
4     Manuel    40            1      7      9

In [51]:
nombres = list(datos['Nombre'])

# Funci√≥n para calcular la similitud coseno entre dos vectores
def similitud_coseno(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    magnitude1 = np.linalg.norm(vector1)
    magnitude2 = np.linalg.norm(vector2)
    similitud = dot_product / (magnitude1 * magnitude2)
    return similitud


print("Seleccionar la primera persona:")
for i, nombre in enumerate(nombres):
    print(f"{i+1}. {nombre}")
persona1_index = nombres.index(input("Ingresa el nombre correspondiente: "))
persona1 = np.array(datos.iloc[persona1_index, 1:])


print("Seleccionar la segunda persona:")
for i, nombre in enumerate(nombres):
    print(f"{i+1}. {nombre}")
persona2_index = nombres.index(input("Ingresa el nombre correspondiente: "))
persona2 = np.array(datos.iloc[persona2_index, 1:])

similitud = similitud_coseno(persona1, persona2)

print(f"La similitud coseno de {nombres[persona1_index]} y {nombres[persona2_index]} es: {similitud:.4f}")

Seleccionar la primera persona:
1. Christian
2. David
3. Jamez
4. Daniel
5. Manuel
Ingresa el nombre correspondiente: Christian
Seleccionar la segunda persona:
1. Christian
2. David
3. Jamez
4. Daniel
5. Manuel
Ingresa el nombre correspondiente: David
La similitud coseno de Christian y David es: 0.9896